FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY service-a ./service-a
RUN go build -o service-a ./service-a

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/service-a .
CMD ["./service-a"]


